# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170619_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 3, 23, 6, 245694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 3, 23, 6, 245095, tzinfo=utc)),
        ),
    ]
